name: Update Research Page

on:
  push:
    paths:
      - papers.xlsx
      - researcher-header.html
      - researcher-footer.html
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install pandas openpyxl pylatexenc

    - name: Generate HTML
      run: python generate_html.py

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add research.html
        git commit -m "Update research.html from papers.xlsx"
        git push
        